Traceback (most recent call last):
  File "/home/luis/miniconda3/envs/dp/lib/python3.10/site-packages/nbclient/client.py", line 778, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/home/luis/miniconda3/envs/dp/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 189, in ensure_async
    result = await obj
  File "/home/luis/miniconda3/envs/dp/lib/python3.10/site-packages/jupyter_client/channels.py", line 315, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/luis/miniconda3/envs/dp/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/luis/miniconda3/envs/dp/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/luis/miniconda3/envs/dp/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/home/luis/miniconda3/envs/dp/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/luis/miniconda3/envs/dp/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/luis/miniconda3/envs/dp/lib/python3.10/site-packages/nbclient/client.py", line 1001, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/home/luis/miniconda3/envs/dp/lib/python3.10/site-packages/nbclient/client.py", line 802, in _async_poll_for_reply
    error_on_timeout_execute_reply = await self._async_handle_timeout(timeout, cell)
  File "/home/luis/miniconda3/envs/dp/lib/python3.10/site-packages/nbclient/client.py", line 852, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 500 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
film_array = np.genfromtxt('/home/luis/Documentos/RD_20x20_300dpi.csv', delimiter=",", comments="#")
D_film = load(film_array, dpi=300)

print(f"D_tps shape: {D_tps.shape}")
print(f"D_film shape: {D_film.shape}")
-------------------

